/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AlbumsController;
import Controllers.ArtistsController;
import Controllers.PlaylistsController;
import Controllers.SongsController;
import Models.Artists;
import Models.Songs;
import java.util.Collection;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author victor
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    //Constructors
    private ArtistsController artistsController = new ArtistsController();
    private SongsController songsController = new SongsController();
    private AlbumsController albumsController = new AlbumsController();
    private PlaylistsController playlistsController = new PlaylistsController();
    
    //Global Variables
    String lastSelection = "";
    String musicFieldText = "";
    String artistsFieldText = "";
    String albumsFieldText = "";

    public Main() {
        initComponents();
        musicFieldText = btnMusicSelected.getText();
        artistsFieldText = btnArtistsSelected.getText();
        albumsFieldText = btnAlbumsSelected.getText();
        lastSelection = musicFieldText;
    }
    
    void changeSelection(String name){
        lastSelection = name;
    }
    
    void changeTextOnButton(JButton button, String name){
        try{
            button.setText(name);
        } 
        catch (Exception e){
            System.out.println("Error: "+e);
        }
    }
    
    void changeTableModel(Collection<T> data, Object[] title){
        int count = 0;
        for(Object mod : title){
            title[count] = mod.toString().toUpperCase();
            count++;
        }
        
        String[][] items = null;
        
        for(int i = 0; i < data.length; i++){
//            items[i] = data.get
        }        
        
        TableModel dataModel = new DefaultTableModel(items, title);
        
        tableOfEveryrthing.setModel(dataModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        leftPanel = new javax.swing.JPanel();
        btnMusicSelected = new javax.swing.JButton();
        btnAlbumsSelected = new javax.swing.JButton();
        btnArtistsSelected = new javax.swing.JButton();
        btnCreateNewPlaylist = new javax.swing.JButton();
        btnRemovePlaylist = new javax.swing.JButton();
        btnEditPlaylist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playlistsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOfEveryrthing = new javax.swing.JTable();
        btnNewItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        btnEditItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnMusicSelected.setText("Musicas");
        btnMusicSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicSelectedActionPerformed(evt);
            }
        });

        btnAlbumsSelected.setText("Albums");
        btnAlbumsSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumsSelectedActionPerformed(evt);
            }
        });

        btnArtistsSelected.setText("Artists");
        btnArtistsSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistsSelectedActionPerformed(evt);
            }
        });

        btnCreateNewPlaylist.setText("Criar Playlist");

        btnRemovePlaylist.setText("Remover");

        btnEditPlaylist.setText("Editar");
        btnEditPlaylist.setToolTipText("");

        playlistsTable.setBorder(null);
        playlistsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(playlistsTable);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMusicSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArtistsSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlbumsSelected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(btnCreateNewPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnRemovePlaylist))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMusicSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlbumsSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArtistsSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemovePlaylist)
                    .addComponent(btnEditPlaylist)
                    .addComponent(btnCreateNewPlaylist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(tableOfEveryrthing);

        btnNewItem.setText("Nova Música");
        btnNewItem.setToolTipText("");
        btnNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemActionPerformed(evt);
            }
        });

        btnRemoveItem.setText("Remover");

        btnEditItem.setText("Editar Item");
        btnEditItem.setToolTipText("");
        btnEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNewItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveItem))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewItem)
                    .addComponent(btnRemoveItem)
                    .addComponent(btnEditItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusicSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicSelectedActionPerformed
        // TODO add your handling code here:
        changeSelection(musicFieldText);
        changeTextOnButton(btnNewItem, ("Nova Música"));
        
        changeTableModel<Songs>(songsController.get(), songsController.getModelFields());
    }//GEN-LAST:event_btnMusicSelectedActionPerformed

    private void btnAlbumsSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumsSelectedActionPerformed
        // TODO add your handling code here:
        changeSelection(albumsFieldText);
        changeTextOnButton(btnNewItem, ("Novo Álbum"));
        changeTableModel<Albums>(albumsController.get(), albumsController.getModelFields());

    }//GEN-LAST:event_btnAlbumsSelectedActionPerformed

    private void btnArtistsSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistsSelectedActionPerformed
        // TODO add your handling code here:
        changeSelection(artistsFieldText);
        changeTextOnButton(btnNewItem, ("Novo Artista"));
        changeTableModel<Artists>(artistsController.get(),artistsController.getModelFields());
    }//GEN-LAST:event_btnArtistsSelectedActionPerformed

    private void btnNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemActionPerformed
        // TODO add your handling code here:
        if (lastSelection.equals(musicFieldText)){
            
        } else if (lastSelection.equals(albumsFieldText)){
            new AlbumsForm().setVisible(true);
        } else {
           artistsController.insert(new Artists("Teste", "Bio"));
        }
    }//GEN-LAST:event_btnNewItemActionPerformed

    private void btnEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbumsSelected;
    private javax.swing.JButton btnArtistsSelected;
    private javax.swing.JButton btnCreateNewPlaylist;
    private javax.swing.JButton btnEditItem;
    private javax.swing.JButton btnEditPlaylist;
    private javax.swing.JButton btnMusicSelected;
    private javax.swing.JButton btnNewItem;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnRemovePlaylist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTable playlistsTable;
    private javax.swing.JTable tableOfEveryrthing;
    // End of variables declaration//GEN-END:variables
}
